name: Basic tests
on:
  pull_request:
    branches:
      - main
jobs:
  Running-some-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: install packages
        run: npm install
      - name: "Unit tests from Mocha"
        run: npm test
      - name: "Linting with ESLint"
        run: npm lint
      - name: "Integration tests from supertest"
        run: npm integration:test
