name: Running tests in a Docker container
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installing dependencies
        run: npm install

      - name: Run Selenium tests in the Docker container
        run: |
          docker run -d --name my-container -v $PWD:/app -w /app ghcr.io/darkshiira/webb22_alm_cicd:main npm run wdio --spec test/e2e/specs/test.e2e.js

      - name: Wait for the container to finish
        run: sleep 10s

      - name: Show container logs
        run: docker logs my-container

      - name: Change npm cache ownership
        run: |
          docker exec my-container chown -R 1001:123 /root/.npm

      - name: Show updated container logs
        run: docker logs my-container

      - name: Remove the container
        run: docker stop my-container && docker rm my-container
