name: Running a container job
on: push

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    # Job steps
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run selenium test on webb22_alm_cicd
        run: docker run ghcr.io/darkshiira/webb22_alm_cicd:main npm run wdio