name: Running a container job
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: ghcr.io/darkshiira/webb22_alm_cicd:main

    services:
      webb22_alm_cicd:
        image: ghcr.io/darkshiira/webb22_alm_cicd@sha256:5a549c6890d3911a2894d522e52c8ad8abd780dfe574f4a959bacd99fde24bee
        ports:
          - 8080:8080
          - 8081:8081
        options: --detach-keys=ctrl-e

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Set npm cache directory
        run: npm config set cache /github/home/.npm-cache

      - name: Install dependencies
        run: npm install

      - name: Install WebDriverIO globally
        run: npm install -g webdriverio

      - name: Run Selenium tests
        run: npm run wdio
