name: Running a container job
on: push

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container:
      image: ghcr.io/darkshiira/webb22_alm_cicd:main

    # Job steps
    steps:
      - uses: actions/checkout@v2
      - name: Run selenium test on webb22_alm_cicd
        run: npm run wdio