name: Running tests in a Docker container
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installing dependencies
        run: npm install

      - name: Run Selenium tests in the Docker container
        run: |
          docker run -d --name my-container -v $PWD:/app -w /app ghcr.io/darkshiira/webb22_alm_cicd:main npm run wdio --config ./wdio.conf.js --spec ./test/e2e/specs/test.e2e.js
          echo "Test execution logs:"
          docker logs my-container
          docker stop my-container && docker rm my-container
