# Does not work, ignore this file!

name: Running tests in a Docker container
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installing dependencies
        run: npm install

      - name: Run Selenium tests in the Docker container
        run: |
          docker run --name my-container -p 8080:3000 -p 9516:9516 -v $PWD:/app -w /app ghcr.io/darkshiira/webb22_alm_cicd:main npm run wdio --spec test/e2e/specs/test.e2e.js
          sleep 5s
          echo "Test execution logs:"
          docker logs my-container
          docker stop my-container && docker rm my-container
